# This is a values.yaml override file for https://github.com/graphops/helm-charts/tree/main/charts/graph-node

graphNodeDefaults:
  env:
    # Graph Node configuration
    IPFS: "https://ipfs.network.thegraph.com"
    GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: "true"
    # Database configuration
    PGHOST: pg-primary-subgraph-data
    PGPORT: 5432
    PGDATABASE: graph

  # Database sensitive/secret information
  secretEnv:
    PGUSER:
      secretName: graph.pg-primary-subgraph-data.credentials.postgresql.acid.zalan.do
      key: username
    PGPASSWORD:
      secretName: graph.pg-primary-subgraph-data.credentials.postgresql.acid.zalan.do
      key: password

graphNodeGroups:
  index:
    replicaCount: 1 # scale me
  query:
    replicaCount: 1 # scale me

chains:
  mainnet:
    shard: primary
    provider:
      - label: eth-mainnet
        url: http://proxyd-eth-mainnet-proxyd.eth-mainnet:8545
        features: [archive, traces]

  # Uncomment if you have deployed gnosis-mainnet and want to index Gnosis subgraphs
  # gnosis:
  #   shard: primary
  #   provider:
  #     - label: gnosis-mainnet
  #       url: http://proxyd-gnosis-mainnet-proxyd.gnosis-mainnet:8545
  #       features: [archive, traces]
