# Example of an inventory for multiple hosts, including a dedicated
# set of control plane nodes and multiple Kubernetes worker nodes

all:
  vars:
    hardened_ssh_port: &hardened-ssh-port <pick_a_port>
  hosts: 
    control-plane-0:
      ansible_host: <ip>
    control-plane-1:
      ansible_host: <ip>
    control-plane-2:
      ansible_host: <ip>
    worker-0:
      ansible_host: <ip>
    worker-1:
      ansible_host: <ip>
    worker-2:
      ansible_host: <ip>
init_group:
  hosts: 
    control-plane-0:
    control-plane-1:
    control-plane-2:
    worker-0:
    worker-1:
    worker-2:
  vars:
    ansible_user: root
    hardened_ssh_port: *hardened-ssh-port
    main_user: &main-user <username>
    become: true
    # uncomment to create lvm volume group
    # lvm_vg: <pick_a_vg_name> # ie. vg1
    # lvm_vg_devices: [ <list_vg_devices> ] # ie. [ /dev/vda1, /dev/vda15 
    # lvm_lv: <pick_a_lv_name> # ie. storage

k0s:
  vars:
    ansible_user: *main-user
    become: true
    k0s_version: v1.24.4+k0s.0
    k0s_use_custom_config: true
    ansible_ssh_port: *hardened-ssh-port
    lb_address: <add_lb_address>
  children:
    initial_controller:
      hosts:
        control-plane-0:
    controller:
      hosts:
        control-plane-1:
        control-plane-2:
    worker:
      hosts:
        worker_0:
        worker_1:
        worker_2:


