# Example of an inventory for multiple hosts, including a dedicated
# set of control plane nodes and multiple Kubernetes worker nodes

all:
  vars:
    hardened_ssh_port: <pick_a_port> &hardened-ssh-port
  hosts: 
    control-plane-0:
      ansible_host: <ip>
    control-plane-1:
      ansible_host: <ip>
    control-plane-2:
      ansible_host: <ip>
    worker-0:
      ansible_host: <ip>
    worker-1:
      ansible_host: <ip>
    worker-2:
      ansible_host: <ip>
init_group:
  hosts: 
    control-plane-0:
    control-plane-1:
    control-plane-2:
    worker-0:
    worker-1:
    worker-2:
  vars:
    ansible_user: root
    hardened_ssh_port: <pick_a_port> &hardened-ssh-port
    main_user: <username>
    become: true

k0s:
  vars:
    ansible_user: <username> &main_user
    become: true
    k0s_version: v1.24.4+k0s.0
    k0s_use_custom_config: true
    ansible_ssh_port: pick_a_port> &hardened-ssh-port
    lb_address: <add_lb_address>
  children:
    initial_controller:
      hosts:
        control-plane-0:
    controller:
      hosts:
        control-plane-1:
        control-plane-2:
    worker:
      hosts:
        worker_0:
        worker_1:
        worker_2:


