## NB: Probably don't edit me
## To make pulling upstream launchpad-starter changes seamless, it's recommended
## to add custom Tasks to Taskfile.ext.yaml to prevent merge conflicts

# https://taskfile.dev/usage/
version: '3'

# For all Tasks, source in these environment variables
dotenv: ['.env', '.env.sample'] # TODO REMOVE SAMPLE

# Import Taskfiles from launchpad-core
includes:
  ext:
    taskfile: Taskfile.ext.yaml
    optional: true
  hosts:
    taskfile: launchpad-core/taskfiles/hosts.yml
    optional: true
  releases:
    taskfile: launchpad-core/taskfiles/releases.yml
    optional: true
  indexer:
    taskfile: launchpad-core/taskfiles/indexer.yml
    optional: true
  launchpad:
    taskfile: launchpad-core/taskfiles/launchpad.yml
    optional: true

# Root Task definitions
tasks:
  default:
    silent: true
    cmds:
    - task launchpad:version
    - |
      echo "When passing arguments to tasks, remember to preceed them with '--'. Example: task help -- releases:apply"
    - echo
    - task --list-all

  help:
    silent: true
    cmds:
      - |
        set - {{.CLI_ARGS}}
        TASK="$1"; shift
        if [ -z "$TASK" ]; then
          echo "You must pass a task as an argument. Example: task help -- task_name"
          echo "To see all available commands, run: task"
          exit 1
        fi
        task --summary $TASK | gum format

  launchpad:pull-upstream-starter:
    desc: Pull changes from upstream launchpad-starter into current branch
    cmds:
    - git remote add pull upstream-starter https://github.com/graphops/launchpad-starter || true
    - |
      if [[ `git status --porcelain --untracked-files=no` ]]; then echo "You have uncommitted changes! Exiting..." && exit 1; fi
    - git status
    - gum confirm "Are you sure you want to pull the main branch of launchpad-starter into the current branch?"
    - git pull starter-upstream main --recurse-submodules --squash

  launchpad:update-core:
    desc: Update the launchpad-core submodule to the latest version
    cmds:
    - git submodule status
    - git submodule add https://github.com/graphops/launchpad-core launchpad-core || true && echo "OK"
    - git submodule update --init --recursive --remote --depth=1
    - git submodule status

  octant:
    desc: Run octant to navigate your cluster in your web browser
    cmds:
    - octant {{.CLI_ARGS}}

  k9s:
    desc: Run k9s to navigate your cluster in your terminal
    cmds:
    - k9s {{.CLI_ARGS}}
