## NB: Probably don't edit me
## To make pulling upstream launchpad-starter changes seamless, it's recommended
## to add custom Tasks to a Taskfile.ext.yaml to prevent merge conflicts
## Any tasks you add to Taskfile.ext.yaml will be available under the ext group

# https://taskfile.dev/usage/
version: '3'

# For all Tasks, source in these environment variables
dotenv: ['.env']

# Import Taskfiles from launchpad-core
includes:
  ext:
    taskfile: Taskfile.ext.yaml
    optional: true
  hosts:
    taskfile: launchpad-core/taskfiles/hosts.yml
    optional: true
  releases:
    taskfile: launchpad-core/taskfiles/releases.yml
    optional: true
  indexer:
    taskfile: launchpad-core/taskfiles/indexer.yml
    optional: true
  launchpad:
    taskfile: launchpad-core/taskfiles/launchpad.yml
    optional: true
  utils:
    taskfile: launchpad-core/taskfiles/utils.yml
    optional: true

# Root Task definitions
tasks:
  # Default task will list all available tasks
  default:
    desc: List all available tasks
    silent: true
    cmds:
    - "task launchpad:version || (echo '\nPlease install the launchpad-core submodule by using: task launchpad:update-core\n' && exit 1)"
    - |
      echo "When passing arguments to tasks, remember to preceed them with '--'. Example: task help -- releases:apply"
    - echo
    - task --list

  help:
    desc: "Display help for a task. Usage: help -- <task name>"
    silent: true
    cmds:
      - |
        set - {{.CLI_ARGS}}
        TASK="$1"; shift
        if [ -z "$TASK" ]; then
          echo "You must pass a task as an argument. Example: task help -- task_name"
          echo "To see all available commands, run: task"
          exit 1
        fi
        task --summary $TASK | gum format

  launchpad:setup:
    desc: Setup launchpad-core and install launchpad dependencies after a fresh clone
    cmds:
    - task launchpad:update-core # provides launchpad:deps
    - task launchpad:deps

  launchpad:update-core: # deps may not be installed, so only use git and bash
    desc: Update the launchpad-core submodule to the latest version
    cmds:
    - git submodule status
    - git submodule add https://github.com/graphops/launchpad-core launchpad-core || true && echo "OK"
    - git submodule update --init --recursive --remote --rebase
    - git submodule status
    - git status
    - echo "Done! Be sure to commit any changes now."

  octant:
    desc: Run octant to navigate your cluster in your web browser
    cmds:
    - octant {{.CLI_ARGS}}

  k9s:
    desc: Run k9s to navigate your cluster in your terminal
    cmds:
    - k9s {{.CLI_ARGS}}
