## NB: Probably don't edit me
## To make pulling upstream launchpad-starter changes seamless, it's recommended
## to add custom Tasks to Taskfile.ext.yaml to prevent merge conflicts

# https://taskfile.dev/usage/
version: '3'

# For all Tasks, source in these environment variables
dotenv: ['.env', '.env.sample'] # TODO REMOVE SAMPLE

# Import Taskfiles from launchpad-core
includes:
  ext:
    taskfile: Taskfile.ext.yaml
    optional: true
  hosts:
    taskfile: launchpad-core/taskfiles/hosts.yml
    optional: true
  releases:
    taskfile: launchpad-core/taskfiles/releases.yml
    optional: true
  indexer:
    taskfile: launchpad-core/taskfiles/indexer.yml
    optional: true
  launchpad:
    taskfile: launchpad-core/taskfiles/launchpad.yml
    optional: true

# Root Task definitions
tasks:
  default:
    silent: true
    cmds:
    - task launchpad:version
    - echo "Available commands:"
    - task --list-all

  launchpad:pull-starter-upstream:
    cmds:
    - task launchpad:version
    - git remote add starter-upstream https://github.com/graphops/launchpad-starter || true
    - |
      [[ `git status --porcelain --untracked-files=no` ]] && echo "You have uncommitted changes! Exiting..." && exit 1
    - git status
    - gum confirm "Are you sure you want to pull starter-upstream/main into the current branch?"
    - git pull starter-upstream main --recurse-submodules --squash

  launchpad:update-core:
    cmds:
    - echo hello # submodule magic

  octant:
    cmds:
    - octant

  k9s:
    cmds:
    - k9s
# operational tasks
# viewing logs
# accessing cli container
# accessing grafana + other remote services
# cleaning subgraph data
# analyse indices
