# https://taskfile.dev/usage/

version: '3'

dotenv: ['.env', '.env.sample'] # TODO REMOVE SAMPLE

# env: 
#   GREETING: Hey, there!

vars:
  # INVENTORY_PATH: "~/infra/ansible/hosts/inventory.yaml"
  # INVENTORY_PATH: "./inventory/inventory.yaml"

includes:
  ext:
    taskfile: Taskfile.ext.yaml
    optional: true
  hosts:
    taskfile: launchpad-core/taskfiles/hosts.yml
    optional: true
  releases:
    taskfile: launchpad-core/taskfiles/releases.yml
    optional: true
  indexer:
    taskfile: launchpad-core/taskfiles/indexer.yml
    optional: true
  # vars:
  #   DOCKER_IMAGE: frontend_image

tasks:
  launchpad:pull-starter-upstream:
    cmds:
    - echo hello # submodule magic
  launchpad:update-core:
    cmds:
    - echo hello # submodule magic
  default:
    cmds: # TODO some kind of help output
    - task --list-all

  octant:
    cmds:
    - octant

  k9s:
    cmds:
    - k9s
# operational tasks
# viewing logs
# accessing cli container
# accessing grafana + other remote services
# cleaning subgraph data
# analyse indices
