all:
  hosts: &all-hosts
    control-plane-0:
      ansible_host: 10.0.0.104
  vars:
    become: true
    k0s_version: v1.24.2+k0s.0
    k0s_binary_dest: /usr/local/bin/k0s
    extra_args: "--enable-worker --no-taints"
    ansible_user: roger # root
    hardened_ssh_port: 987
    ansible_ssh_port: 987
    main_user: roger
  children:
    init_group:
      hosts: *all-hosts
      vars:
        ansible_ssh_port: 22
    k0s:
      children:
        initial_controller:
          hosts:
            control-plane-0:
      vars:
        ansible_ssh_port: 987