# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/eth-mainnet.yaml" }}

releases:
  - name: nimbus-eth-mainnet
    <<: *launchpad-release-template-nimbus-eth-mainnet
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: erigon-archive-trace-eth-mainnet
    <<: *launchpad-release-template-erigon-eth-mainnet
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: proxyd-eth-mainnet
    <<: *launchpad-release-template-proxyd-eth-mainnet
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
