# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/indexer.yaml" }}

releases:
  - name: postgresql-cr
    <<: *launchpad-release-template-postgresql-cr
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: graph-node
    <<: *launchpad-release-template-graph-node
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: graph-operator-mnemonic
    <<: *launchpad-release-template-defaults
    chart: graphops/resource-injector
    version: 0.2.0
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: graph-network-indexer
    <<: *launchpad-release-template-graph-network-indexer
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: graph-toolbox
    <<: *launchpad-release-template-defaults
    chart: graph-network-indexer-chart-dev/graph-toolbox
    # version: 4.2.1
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
