# Import YAML template definitions from launchpad-core
{{ readFile "../../launchpad-core/helmfiles/templates/ingress.yaml" }}

releases:
  - name: ingress-nginx
    <<: *launchpad-release-template-ingress-nginx
    missingFileHandler: Warn
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml