# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions from launchpad-core
{{ readFile "../../launchpad-core/helmfiles/templates/ingress.yaml" }}

releases:
  - name: ingress-nginx
    <<: *launchpad-release-template-ingress-nginx
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: cert-manager
    <<: *launchpad-release-template-cert-manager
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: cert-manager-resources
    <<: *launchpad-release-template-resource-injector
    disableValidationOnInstall: true # For CRDs https://github.com/helmfile/helmfile/blob/main/pkg/state/state.go#L236
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
