# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions from launchpad-core
{{ readFile "../../launchpad-core/helmfiles/templates/monitoring.yaml" }}

releases:
  - name: kube-prometheus-stack
    <<: *launchpad-release-template-kube-prometheus-stack
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: loki
    <<: *launchpad-release-template-loki
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: promtail
    <<: *launchpad-release-template-promtail
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: node-problem-detector
    <<: *launchpad-release-template-node-problem-detector
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
