# Import YAML template definitions from launchpad-core
{{ readFile "../../launchpad-core/helmfiles/templates/monitoring.yaml" }}

releases:
  - name: promtail
    <<: *launchpad-release-template-promtail
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: grafana
    <<: *launchpad-release-template-grafana
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: prometheus
    <<: *launchpad-release-template-prometheus
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: loki-secret
    <<: *launchpad-release-template-loki-secret
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: loki
    <<: *launchpad-release-template-loki
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

# For more advanced customisation of the releases in the namespace and their configuration
# See https://docs.graphops.xyz/launchpad/defining-releases TODO TODO TODO
