# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions from launchpad-core
{{ readFile "../../launchpad-core/helmfiles/templates/postgres-operator.yaml" }}

releases:
  - name: postgres-operator
    <<: *launchpad-release-template-postgres-operator
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
