# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/sealed-secrets.yaml" }}

releases:
  - name: sealed-secrets
    <<: *launchpad-release-template-sealed-secrets
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

# For more advanced customisation of the releases in the namespace and their configuration
# See https://docs.graphops.xyz/launchpad/defining-releases TODO TODO TODO
