# Import base configuration
bases:
- _base.yaml

# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/storage.yaml" }}

releases:
  - name: openebs
    <<: *launchpad-release-template-openebs
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: openebs-rawfile-localpv
    <<: *launchpad-release-template-openebs-rawfile-localpv
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  - name: openebs-rawfile-storageclass
    <<: *launchpad-release-template-resource-injector
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

  # Enable deployment of the openebs-zfs-localpv releases if you intend to use OpenEBS ZFS LocalPVs
  # - name: openebs-zfs-localpv
  #   <<: *launchpad-release-template-openebs-zfs-localpv
  #   values:
  #     - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
  # - name: openebs-zfs-storageclass
  #   <<: *launchpad-release-template-resource-injector
  #   values:
  #     - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
