# Import YAML template definitions
{{ readFile "../../launchpad-core/helmfiles/templates/storage.yaml" }}

releases:
  - name: openebs
    <<: *launchpad-release-template-openebs
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
  - name: openebs-rawfile-localpv
    <<: *launchpad-release-template-openebs-rawfile-localpv
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml
  - name: openebs-rawfile-storageclass
    <<: *launchpad-release-template-openebs-rawfile-storageclass
    values:
      - ../release-values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}.yaml

# For more advanced customisation of the releases in the namespace and their configuration
# See https://docs.graphops.xyz/launchpad/defining-releases TODO TODO TODO
