# Release values overrides for graph-node
toolbox:
  enabled: false

graphNodeDefaults:
  env:
    PGHOST: pg-graph-node
    PGPORT: 5432
    PGDATABASE: graph
    ETH_MAINNET_RPC_URL:
    GRAPH_POI_ACCESS_TOKEN: SOMETHING_RANDOM

  secretEnv:
    PGUSER:
      secretName: graph.pg-graph-node.credentials.postgresql.acid.zalan.do
      key: username
    PGPASSWORD:
      secretName: graph.pg-graph-node.credentials.postgresql.acid.zalan.do
      key: password
