# Release values overrides for graph-node
graphNodeDefaults:
  env:
    # Database configuration
    PGHOST: pg-graph-node
    PGPORT: 5432
    PGDATABASE: graph
    GRAPH_POI_ACCESS_TOKEN: CHANGE_ME_TO_SOMETHING_RANDOM # securely generate using: openssl rand -hex 32
    # Blockchain node configuration
    ETH_MAINNET_RPC_URL: http://proxyd-eth-mainnet-proxyd.eth-mainnet:8545

  secretEnv:
    PGUSER:
      secretName: graph.pg-graph-node.credentials.postgresql.acid.zalan.do
      key: username
    PGPASSWORD:
      secretName: graph.pg-graph-node.credentials.postgresql.acid.zalan.do
      key: password
